### ISSUE TITLE
Switch to BSD license

### ISSUE THREAD

**Issue by fhoefling** [fhoefling/h5xx#3]
I would like to re-license this project under the modified (i.e. 3-clause) BSD license. The motivation is to have the greatest possible outreach. The BSD license is FOSS compatible and gives greatest flexibility with respect to use in other free of proprietary software without giving up our authorship rights.

Before the code can be placed under the new license, I need the written permission from every author. Therefore I ask all of you kindly to support the re-licensing by a one-line statement in reply to this issue. For example: "I agree that my contributions to the h5xx project until this point of writing are distributed under the terms of the 3-clause BSD license."

The terms of the 3-clause BSD license are quoted  below.

Thanks a lot for your cooperation.

Felix

> Copyright (c) [year], [copyright holder]
> All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are met:
>     \* Redistributions of source code must retain the above copyright
>       notice, this list of conditions and the following disclaimer.
>     \* Redistributions in binary form must reproduce the above copyright
>       notice, this list of conditions and the following disclaimer in the
>       documentation and/or other materials provided with the distribution.
>     \* Neither the name of the [organization] nor the
>       names of its contributors may be used to endorse or promote products
>       derived from this software without specific prior written permission.
> 
> [WARRANTY DISCLAIMER]

**Comment by the-nic** [comment]
I agree that my contributions to the h5xx project until this point of writing are distributed under the terms of the 3-clause BSD license.

Nicolas

**Comment by reuterk** [comment]
I agree that my contributions to the h5xx project until this point of writing are distributed under the terms of the 3-clause BSD license.

Best regards,
Klaus

**Comment by petercolberg** [comment]
I agree that my contributions to the h5xx project until this point of writing are distributed under the terms of the 3-clause BSD license.

Peter

**Comment by fhoefling** [comment]
For completeness:

I agree that my contributions to the h5xx project until this point of writing are distributed under the terms of the 3-clause BSD license.

Felix

**Comment by dibakma** [comment]
I agree that my contributions to the h5xx project until this point of writing are distributed under the terms of the 3-clause BSD license.

Manuel
